python main.py ^
    --do_train ^
    --train_file data/cnn_dailymail_svo_train.json ^
    --validation_file data/cnn_dailymail_svo_test.json ^
    --prompt_column article ^
    --response_column highlights ^
    --overwrite_cache ^
    --model_name_or_path THUDM/chatglm-6b ^
    --output_dir output/adgen-chatglm-6b-pt-$PRE_SEQ_LEN-$LR ^
    --overwrite_output_dir ^
    --max_source_length 1024 ^
    --max_target_length 256 ^
    --per_device_train_batch_size 4 ^
    --per_device_eval_batch_size 4 ^
    --gradient_accumulation_steps 4 ^
    --predict_with_generate ^
    --max_steps 3000 ^
    --logging_steps 10 ^
    --save_steps 1000 ^
    --learning_rate 2e-2 ^
    --pre_seq_len 128 ^
    --preprocessing_num_workers 15

